### ISSUE TITLE
Unexpected warning of register_model

### ISSUE THREAD

**Issue by lu-ming-lei** [xinghaochen/TinySAM#13]
UserWarning: Overwriting tiny_vit_5m_224 in registry with tinysam.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)

I got several warings when running demo.py and this is my outcome. I want to know if the result is normal and if this warning can be ignored since my pytorch version is higher.

![test](https://github.com/xinghaochen/TinySAM/assets/55871206/914ba0ac-ca8e-45c4-bd38-9be09cfa561b)

**Comment by Cbtor** [comment]
Hi @lu-ming-lei , we cannot reproduce this warning in our test environment. From the description of this warning, it could be caused by conflicts with other libraries which also use the function name `tiny_vit_5m_224`. Maybe you can solve this warning by creating a new virtual environment for TinySAM.

The final output seems normal and I think there is nothing to do with the version of PyTorch.

**Comment by Gaffey** [comment]
Hi @lu-ming-lei , we cannot reproduce this warning in our test environment. From the description of this warning, it could be caused by conflicts with other libraries which also use the function name `tiny_vit_5m_224`. Maybe you can solve this warning by creating a new virtual environment for TinySAM.

The final output seems normal and I think there is nothing to do with the version of PyTorch.

**Comment by TimyWimey** [comment]
@lu-ming-lei  I also received the same warning, with 5 similar contents 
```
tiny_vit_sam.py:656: UserWarning: Overwriting tiny_vit_5m_224 in registry with tinysam.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
```

May I ask if you solved this problem?

**Comment by StevenHaojc** [comment]
I receive the same problem too.

**Comment by xinghaochen** [comment]
You could simply ignore this warning. This warning occurs due to conflict names of the [timm model](https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/tiny_vit.py) and our [model](https://github.com/xinghaochen/TinySAM/blob/main/tinysam/modeling/tiny_vit_sam.py#L660). See the [registry function](https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/_registry.py#L24) in timm  for more details.

This warning does not affect the usage of TinySAM.
